### ISSUE TITLE
Specify Utility Bounds for a Power

### ISSUE THREAD

**Issue by Wert5** [SHADE-AI/daidepp#17]
**What functionality will your new tokens add?**
Add a new arrangement that specifies utility upper/lower bound for a particular power. This is intended for use with threats to show how much cooperation benefits the receiver over the threatened punishment.

**Describe the precise changes you'd like**
- New token ULB used to specify utility lower bound for a power.
- New token UUB used to specify utility upper bound for a power.
- Daide clauses would be in the format (ULB power float) or  (UUB power float) 
- Float is a new nonterminal representing a floating point number in some format that can easily be parsed from python
- Added to lowest new DAIDE level, which I think is 140
- Example usage: England sends Germany IFF (XDO((GER AMY BER) MTO MUN)) THN (PRP (ULB GER 0.8)) ELS (INS (UUB GER 0.1))
- This is a threat from England to Germany that says if you move BER to MUN then I will move to give you at least 0.8 utility, but if you do anything else I will move to prevent you from getting more than 0.1 utility.
- In this case the utility represents England's estimate of Germany's utility
- Different bots may have different ideas of utility that are not comparable, but providing the utility estimates from the same bot for different potential actions can emphasize that a threat is serious and make it clearer when something is considered a threat
- It could also be used outside threats for expressing preferences during negotiations
- Should be simple to implement because it does not wrap any other messages
- Requires adding floating point parsing, but that is built into python so it should not be too bad
- If people are very resistant to adding floats, we could use the existing ints and just multiply utilities by 100 before sending

**Comment by mjspeck** [comment]
My comments from the meeting today:
- make a fork for this update and put in level 140
- Treat `ULB` and `UUB` as press messages instead of agreements (i.e. they don't need to be wrapped by `PRP` or `INS`).
