### ISSUE TITLE
Support DAIDE string construction from keyword tokens

### ISSUE THREAD

**Issue by trigaten** [SHADE-AI/daidepp#26]
I am from SHADE and would like to use this library as our main parser. We are currently using this library: https://github.com/trigaten/DAIDE, which provides simple parsing, as well as DAIDE message construction using DAIDE keywords, like the following:

```python
# easily compose DAIDE keywords
>>> from DAIDE import Order, Unit, ORR, HLD
>>> arrangement = ORR([Order(Unit("FFF FFF FFF"), HLD()), Order(Unit("FFF FFF FFF"), HLD())])
>>> str(arrangement)
'ORR ((FFF FFF FFF) HLD) ((FFF FFF FFF) HLD)'
```

It would be very useful if your parser provided this support. How difficult would this be to add?

**Comment by mjspeck** [comment]
It's not too difficult, but I wouldn't be able to promise anything before the upcoming milestone.

**Comment by mjspeck** [comment]
@trigaten we're starting work on this now. Will keep you updated
